import Head from 'next/head';
import Nav from '../components/Nav/Nav';
import Blogs from './blogsPage/Blogs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Blogs />
    </div>
  );
}
